// Regenerate index secgrid + sitemap from manifest.json and the built SECTIONS.
const fs = require('fs');
const path = require('path');
const SITE = path.resolve(__dirname, '..');            // opix-site root
const MAN = path.join(__dirname, 'manifest.json');     // tools/manifest.json
const manifest = JSON.parse(fs.readFileSync(MAN, 'utf8'));
const { SECTIONS } = require(path.join(SITE, 'data', 'products.js'));
const { sectionCard } = require('./card_assets.js');

const esc = s => s.replace(/&/g, '&amp;');

// ---- index secgrid ----
const cards = manifest.map(m => {
  const built = SECTIONS[m.code] && SECTIONS[m.code].items.length;
  if (built) return sectionCard(m.code, m, SECTIONS, '    ');
  return `    <a class="seccard soon"><span class="sc-code">${m.code}</span><h3>${esc(m.title)}</h3><p>Coming online soon</p></a>`;
}).join('\n');

let idx = fs.readFileSync(SITE + '/index.html', 'utf8');
idx = idx.replace(/(<div class="secgrid">)[\s\S]*?(\n  <\/div>)/, `$1\n${cards}$2`);
fs.writeFileSync(SITE + '/index.html', idx);

// ---- sitemap ----
// Sitemaps are NOT written here any more. tools/seo/build.js emits a sitemap
// index plus paginated child sitemaps covering the 286 category landing pages
// and the image-sitemap entries — none of which this script knows about.
// Writing a flat sitemap.xml from here would silently drop ~290 URLs.

const builtList = manifest.filter(m => SECTIONS[m.code] && SECTIONS[m.code].items.length).map(m => m.code);
console.log('regen done. built sections:', builtList.join(', '), '(' + builtList.length + ')');

// The catalogue pages, category pages and sitemaps are all generated by the SEO
// build, which is also what pre-renders the products into the served HTML.
// Running regen without it leaves the home-page grid updated but the catalogue
// pages stale, so chain it here rather than rely on remembering.
console.log('running the SEO build...');
require('child_process').execFileSync(process.execPath,
  [require('path').join(__dirname, 'seo', 'build.js')], { stdio: 'inherit' });
